[package]
name = "benefit-scenario"
version = "0.1.0"
edition = "2024"
authors = ["Richard M. Hamilton"]
description = "Employee benefit cost-sharing scenario engine"
repository = "https://github.com/rhamenator/BenefitScenario"

[package.metadata.wix]
upgrade-guid = "2ED6503C-77C6-416B-B74F-F3FF8EB78B4F"
path-guid = "1457E1E1-637C-4EF8-BB6A-41C3BA1FCB38"
license = false
eula = false

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
